name: Sync OAS to ReadMe
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    environment: NONMASTER
    steps:
      - uses: actions/checkout@v3
      - uses: readmeio/rdme@main
        with:
          rdme: openapi backend/docs/openapi.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_API_DEFINITION_ID }}
